### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by daniel-v** [angulardart/angular#1976]
I think it's fitting to express my gratitude with the release of 7.0.0

This is to everyone to created, maintained or contributed Angular Dart and it's libraries:

## THANK YOU

for years of work.

**Comment by kevmoo** [comment]
🥲  Thanks, @daniel-v – from everyone!

**Comment by KevinBLT** [comment]
I would also like to add thanks to everyone keeping this up-to-date ! :-)

Yeah, we know flutter and all - but still we handle to be much more effective with this library when target web is the primary build target. Dart is - at least for me - ahead of every web alternative, yet with angular dart we have still native HTML web application (flutter, although it works better and better often just feels, you know ... "odd"?)

Please keep on going, we know google is using this internally, so progress is being made, although I am not quite sure about the decision where google decided to keep the code of all its products/projects in this huge repo :-)

**Comment by mit-mit** [comment]
### AngularDart development has transitioned to the `angulardart-community` project

The AngularDart team at Google has transitioned the maintenance of the AngularDart project to the [`angulardart-community` project](https://github.com/angulardart-community). We will no longer accept issues or pull requests on the current repo, which has been archived to avoid confusion.

The project was originally maintained by the AngularDart team at Google, but due to a shift to prioritize internal usage of AngularDart and increased emphasis on Flutter's web support, we [in 2021 asked for community contributors](https://medium.com/dartlang/angulardart-flutter-and-the-web-spring-update-f7f5b8b10001) that might be interested in taking over AngularDart. We're very happy that the angulardart-community has come forward to take over the maintenance of AngularDart.

For more details about the angulardart-community project, see [their roadmap issue](https://github.com/angulardart-community/angular/issues/6).

For developers excited to use Dart & Flutter for building new apps for the Web, we'd encourage you to look at [Flutter Web](https://flutter.dev/web).
